<a href="https://colab.research.google.com/github/2403a53044/ml_lab/blob/main/mllab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/Salary_dataset.csv')
df

    Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22          22              8.0  101303.0
23          23              8.3  113813.0
24          24              8.8  109432.0
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [ ]:
df.head()

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [ ]:
df.tail()

    Unnamed: 0  YearsExperience    Salary
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [ ]:
x=df.YearsExperience
y=df.Salary
x

0      1.2
1      1.4
2      1.6
3      2.1
4      2.3
5      3.0
6      3.1
7      3.3
8      3.3
9      3.8
10     4.0
11     4.1
12     4.1
13     4.2
14     4.6
15     5.0
16     5.2
17     5.4
18     6.0
19     6.1
20     6.9
21     7.2
22     8.0
23     8.3
24     8.8
25     9.1
26     9.6
27     9.7
28    10.4
29    10.6
Name: YearsExperience, dtype: float64

In [ ]:
import numpy as np
x=np.array(x)
y=np.array(y)
x

array([ 1.2,  1.4,  1.6,  2.1,  2.3,  3. ,  3.1,  3.3,  3.3,  3.8,  4. ,
        4.1,  4.1,  4.2,  4.6,  5. ,  5.2,  5.4,  6. ,  6.1,  6.9,  7.2,
        8. ,  8.3,  8.8,  9.1,  9.6,  9.7, 10.4, 10.6])

In [ ]:
y

array([ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
        54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
        61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
        98274., 101303., 113813., 109432., 105583., 116970., 112636.,
       122392., 121873.])

In [ ]:
x=df.iloc[:,1].values
x

array([ 1.2,  1.4,  1.6,  2.1,  2.3,  3. ,  3.1,  3.3,  3.3,  3.8,  4. ,
        4.1,  4.1,  4.2,  4.6,  5. ,  5.2,  5.4,  6. ,  6.1,  6.9,  7.2,
        8. ,  8.3,  8.8,  9.1,  9.6,  9.7, 10.4, 10.6])

In [ ]:
y=df.iloc[:,-1].values
y

array([ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
        54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
        61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
        98274., 101303., 113813., 109432., 105583., 116970., 112636.,
       122392., 121873.])

In [ ]:
x=x.reshape(-1,1)
x

array([[ 1.2],
       [ 1.4],
       [ 1.6],
       [ 2.1],
       [ 2.3],
       [ 3. ],
       [ 3.1],
       [ 3.3],
       [ 3.3],
       [ 3.8],
       [ 4. ],
       [ 4.1],
       [ 4.1],
       [ 4.2],
       [ 4.6],
       [ 5. ],
       [ 5.2],
       [ 5.4],
       [ 6. ],
       [ 6.1],
       [ 6.9],
       [ 7.2],
       [ 8. ],
       [ 8.3],
       [ 8.8],
       [ 9.1],
       [ 9.6],
       [ 9.7],
       [10.4],
       [10.6]])

In [ ]:
min=reshape.min()
max=reshape.max()
min
max

np.float64(10.6)

In [ ]:
m=np.min(y)
m

np.float64(37732.0)

In [ ]:
ma=np.max(y)
ma

np.float64(122392.0)

In [ ]:
x_std=x.std()
x_stand=(x-x.mean())/x_std
x_stand

array([[-1.51005294],
       [-1.43837321],
       [-1.36669348],
       [-1.18749416],
       [-1.11581443],
       [-0.86493538],
       [-0.82909552],
       [-0.75741579],
       [-0.75741579],
       [-0.57821647],
       [-0.50653674],
       [-0.47069688],
       [-0.47069688],
       [-0.43485702],
       [-0.29149756],
       [-0.1481381 ],
       [-0.07645838],
       [-0.00477865],
       [ 0.21026054],
       [ 0.2461004 ],
       [ 0.53281931],
       [ 0.6403389 ],
       [ 0.92705781],
       [ 1.03457741],
       [ 1.21377673],
       [ 1.32129632],
       [ 1.50049564],
       [ 1.5363355 ],
       [ 1.78721455],
       [ 1.85889428]])

In [ ]:
normalization=(x-x.min())/(x.max()-x.min())
normalization

array([[0.        ],
       [0.0212766 ],
       [0.04255319],
       [0.09574468],
       [0.11702128],
       [0.19148936],
       [0.20212766],
       [0.22340426],
       [0.22340426],
       [0.27659574],
       [0.29787234],
       [0.30851064],
       [0.30851064],
       [0.31914894],
       [0.36170213],
       [0.40425532],
       [0.42553191],
       [0.44680851],
       [0.5106383 ],
       [0.5212766 ],
       [0.60638298],
       [0.63829787],
       [0.72340426],
       [0.75531915],
       [0.80851064],
       [0.84042553],
       [0.89361702],
       [0.90425532],
       [0.9787234 ],
       [1.        ]])

In [ ]:
a=np.random.randn()
b=np.random.randn()
print("Randomly initialized slope:",a)
print("Randomly initialized intercept:",b)

Randomly initialized slope: 1.4729625101049657
Randomly initialized intercept: 0.295245293255388

In [ ]:
def predict(x,a,b):
  y_pred= a*x+b
  return y_pred

In [ ]:
y_pred=predict(normalization,a,b)
y_pred

array([[0.29524529],
       [0.32658492],
       [0.35792455],
       [0.43627362],
       [0.46761325],
       [0.57730194],
       [0.59297176],
       [0.62431139],
       [0.62431139],
       [0.70266046],
       [0.73400008],
       [0.7496699 ],
       [0.7496699 ],
       [0.76533971],
       [0.82801897],
       [0.89069822],
       [0.92203785],
       [0.95337748],
       [1.04739636],
       [1.06306618],
       [1.18842469],
       [1.23543413],
       [1.36079264],
       [1.40780208],
       [1.48615115],
       [1.53316059],
       [1.61150966],
       [1.62717948],
       [1.73686818],
       [1.7682078 ]])

In [ ]:
print("First 5 predicted values:")
print(y_pred[:5])
print("Actual values:")
print(y[:5])

First 5 predicted values:
[[0.29524529]
 [0.32658492]
 [0.35792455]
 [0.43627362]
 [0.46761325]]
Actual values:
[39344. 46206. 37732. 43526. 39892.]

In [ ]:
#mean squad error
def compute_cost(y,y_pred):
  m=len(y)
  cost=(1/2*m)*np.sum((y-y_pred)**2)
  return cost

In [ ]:
#compute initial cost
cost=compute_cost(y,y_pred)
print("Initial cost (MSE):",cost)

Initial cost (MSE): 87789987543267.39

In [ ]:
#compute prediction for given parameters
y_pred=predict(normalization,a,b)

In [ ]:
a=0.0
b=0.0
y_pred=predict(normalization,a,b)
cost=compute_cost(y,y_pred)
print("cost for a=",a,"b",b,"is",cost)

cost for a= 0.0 b 0.0 is 87791948249400.0

In [ ]:
learning_rate=0.01
epochs=1000
print("learning rate",learning_rate)
print("epochs",epochs)

learning rate 0.01
epochs 1000

In [ ]:
n=len(y)

In [ ]:
cost_history=[]

In [ ]:
for epoch in range(epochs):
  y_pred=predict(normalization,a,b)
  da=(1/n)*np.sum((y_pred-y)*normalization)
  db=(1/n)*np.sum(y_pred-y)
  a=a-learning_rate*da
  b=b-learning_rate*db
  cost=compute_cost(y,y_pred)
  cost_history.append(cost)
  if epoch%100==0:
    print("Epoch=",epoch,"cost=",cost)

Epoch= 0 cost= 9807740033400.0
Epoch= 100 cost= 9807740033400.0
Epoch= 200 cost= 9807740033400.0
Epoch= 300 cost= 9807740033400.0
Epoch= 400 cost= 9807740033400.0
Epoch= 500 cost= 9807740033400.0
Epoch= 600 cost= 9807740033400.0
Epoch= 700 cost= 9807740033400.0
Epoch= 800 cost= 9807740033400.0
Epoch= 900 cost= 9807740033400.0

In [ ]:
final_slope=a
final_intercept=b
print("Final slope:",final_slope)
print("Final intercept:",final_intercept)

Final slope: 1.1158631990601413e-10
Final intercept: 76003.99999999993

In [ ]:
def predict_salary(YearsExperience,a,b,x_min_train,x_max_train):
  x_to_predict=np.array(YearsExperience).reshape(-1,1)
  normalization=(x_to_predict-x_min_train)/(x_max_train-x_min_train)
  salary_pred=a*normalization+b
  return salary_pred

In [ ]:
year=5
predicted_salary=predict_salary(year,final_slope,final_intercept,min,max)
print("Predicted salary for",year,"years of experience:",predicted_salary)
print(predicted_salary[0][0])

Predicted salary for 5 years of experience: [[76004.]]
76003.99999999997

In [ ]:
-